/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TableImport } from './routes/table'

// Create Virtual Routes

const QueryLazyImport = createFileRoute('/query')()
const FormLazyImport = createFileRoute('/form')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const QueryLazyRoute = QueryLazyImport.update({
  path: '/query',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/query.lazy').then((d) => d.Route))

const FormLazyRoute = FormLazyImport.update({
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const TableRoute = TableImport.update({
  path: '/table',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/table': {
      preLoaderRoute: typeof TableImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      preLoaderRoute: typeof QueryLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  TableRoute,
  FormLazyRoute,
  QueryLazyRoute,
])

/* prettier-ignore-end */
